<?php

use Illuminate\Database\Seeder;

class ITEMIMAGE_SEEDER extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('ITEMIMAGE')->delete();
      DB::table('ITEMIMAGE')->insert([
         'id'=>1,
         'url'=>'/img/O1.jpg',
         'itemID'=>1
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>2,
        'url'=>'/img/O2.jpg',
        'itemID'=>1
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>3,
        'url'=>'/img/O3.jpg',
        'itemID'=>1
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>4,
        'url'=>'/img/O4.jpg',
        'itemID'=>2
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>5,
        'url'=>'/img/O5.jpg',
        'itemID'=>2
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>6,
        'url'=>'/img/O6.jpg',
        'itemID'=>3
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>7,
        'url'=>'/img/O7.jpg',
        'itemID'=>3
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>8,
        'url'=>'/img/O8.jpg',
        'itemID'=>4
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>9,
        'url'=>'/img/O9.jpg',
        'itemID'=>4
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>10,
        'url'=>'/img/M1.jpg',
        'itemID'=>5
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>11,
        'url'=>'/img/M2.jpg',
        'itemID'=>5
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>12,
        'url'=>'/img/M3.jpg',
        'itemID'=>6
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>13,
        'url'=>'/img/M4.jpg',
        'itemID'=>6
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>14,
        'url'=>'/img/M5.jpg',
        'itemID'=>7
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>15,
        'url'=>'/img/M6.jpg',
        'itemID'=>7
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>16,
        'url'=>'/img/C01.jpg',
        'itemID'=>8
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>17,
        'url'=>'/img/C02.jpg',
        'itemID'=>8
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>18,
        'url'=>'/img/C03.jpg',
        'itemID'=>9
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>19,
        'url'=>'/img/C04.jpg',
        'itemID'=>9
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>20,
        'url'=>'/img/C05.JPG',
        'itemID'=>10
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>21,
        'url'=>'/img/C06.JPG',
        'itemID'=>10
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>22,
        'url'=>'/img/C07.JPG',
        'itemID'=>10
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>23,
        'url'=>'/img/C08.JPG',
        'itemID'=>11
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>24,
        'url'=>'/img/C09.JPG',
        'itemID'=>11
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>25,
        'url'=>'/img/C10.JPG',
        'itemID'=>12
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>26,
        'url'=>'/img/C11.JPG',
        'itemID'=>12
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>27,
        'url'=>'/img/C12.JPG',
        'itemID'=>13
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>28,
        'url'=>'/img/C13.JPG',
        'itemID'=>13
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>29,
        'url'=>'/img/C14.JPG',
        'itemID'=>14
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>30,
        'url'=>'/img/C15.JPG',
        'itemID'=>14
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>31,
        'url'=>'/img/C16.jpg',
        'itemID'=>15
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>32,
        'url'=>'/img/C17.jpg',
        'itemID'=>16
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>33,
        'url'=>'/img/C18.jpg',
        'itemID'=>17
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>34,
        'url'=>'/img/D1.jpg',
        'itemID'=>18
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>35,
        'url'=>'/img/D2.JPG',
        'itemID'=>19
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>36,
        'url'=>'/img/K01.jpg',
        'itemID'=>20
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>37,
        'url'=>'/img/K02.jpg',
        'itemID'=>20
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>38,
        'url'=>'/img/K03.jpg',
        'itemID'=>20
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>39,
        'url'=>'/img/K04.jpg',
        'itemID'=>21
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>40,
        'url'=>'/img/K05.jpg',
        'itemID'=>21
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>41,
        'url'=>'/img/K06.jpg',
        'itemID'=>21
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>42,
        'url'=>'/img/K07.jpg',
        'itemID'=>21
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>43,
        'url'=>'/img/K08.jpg',
        'itemID'=>21
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>44,
        'url'=>'/img/K09.jpg',
        'itemID'=>22
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>45,
        'url'=>'/img/K10.jpg',
        'itemID'=>22
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>46,
        'url'=>'/img/K11.jpg',
        'itemID'=>22
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>47,
        'url'=>'/img/K12.jpg',
        'itemID'=>22
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>48,
        'url'=>'/img/K13.jpg',
        'itemID'=>22
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>49,
        'url'=>'/img/T1.jpg',
        'itemID'=>23
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>50,
        'url'=>'/img/T2.JPG',
        'itemID'=>24
      ]);
      DB::table('ITEMIMAGE')->insert([
        'id'=>51,
        'url'=>'/img/T3.jpg',
        'itemID'=>25
      ]);
    }
}
